@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

    Class Main{
    +static void main (String[] args)
    }

    Interface Player{
    +int getPoints();
    +String getName();
    +void addPoints(double pointsToAdd);
    }

    Class JuniorPlayer{
    -String name;
    -int points;

    +JuniorPlayer(String name);
    +int getPoints();
    +String getName();
    +void addPoints(double pointsToAdd);
    -int customRound(double score);
    +String toString();
    }

    Class StandardPlayer{
    -String name;
    -int points;

    +StandardPlayer(String name);
    +int getPoints();
    +String getName();
    +void addPoints(double pointsToAdd);
    +String toString();
    }

    Class Team{
    -String teamName;
    -List<Player> playerList;

    +Team(String teamName, List<Player> playerList);
    +int getPoints();
    +String getName();
    +void addPoints(double pointsToAdd);
    -int customRound(double score);
    +void displayTeamMembers();
    +String toString();
    }

    Class Tournament{
    -String name;
    -List<Player> playerList;

    +Tournament(String name, List<Player> playerList);
    +double getAverage();
    +void addPlayer(Player player);
    +String toString();
    }


    JuniorPlayer ..|> Player
    StandardPlayer ..|> Player
    Team ..|> Player
    Tournament o-- Team
    Tournament o-- StandardPlayer
    Tournament o-- JuniorPlayer
    Team o-- JuniorPlayer
    Team o-- StandardPlayer

@enduml

implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--