@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

        Class Main{
        +static void main (String[] args)
        }

        Class Flower{
        -String colour;

        +Flower(String species, LocalDate datePlanted, String colour);
        +String getColour();
        +String toString();
        }

        Class FruitTree{
        -List<Float> yieldList;

        +FruitTree(String species, LocalDate datePlanted, float height);
        +void registerYield(float yeild);
        +float getAverageYield();
        +String toString();
        }

        Class Garden{
        -List<Plant> plantList;

        +Garden();
        +addPlant(Plant plant);
        +void getTotalAverageYield();
        +void displayFlowersOfColour(String colour);
        +void displayTreesHigherThan(float meter);
        }

        Class Plant{
        -String species;
        -LocalDate datePlanted;

        +String getSpecies();
        +LocalDate getDatePlanted();
        }

        Class Tree{
        -Float height;

        +Tree(String species, LocalDate datePlanted, float height);
        +float getHeight();
        +String toString();
        }


        Garden *-- Plant
        Plant <|-- Flower
        Plant <|-- Tree
        Tree <|-- FruitTree





@enduml

implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--