@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

    Class Main{
    +static void main (String[] args)
    }

    Class Die{
    -int sides;
    -Random random;

    +Die(int sides);
    +int throwDie();
    +int getSides();
    }

    Class Statistics{
    -Die die;

    +Statistics(Die die);
    +int[] results(int numberOfThrows);
    +void displayResults(int numberOfThrows);
    +void displayExpectedProbabilities(int numberOfThrows);
    }

    Die o-- Statistics



@enduml

implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--